rtl/common/TypesPkg.sv
rtl/frontend/bpu/BimodalPredictor.sv
rtl/frontend/bpu/LoopPredictor.sv
rtl/frontend/bpu/TageFoldedHistory.sv
rtl/frontend/bpu/TageHash.sv
rtl/frontend/bpu/TageUpdateQueue.sv
rtl/frontend/bpu/TageTable.sv
rtl/frontend/bpu/ScSignedCounterTable.sv
rtl/frontend/bpu/StatisticalCorrector.sv
rtl/frontend/bpu/TagePredictor.sv
verification/perf/cbp/CbpRtlPredictor.sv
