rtl/frontend/decode/Decoder.sv
rtl/frontend/bpu/BranchTargetBuffer.sv
rtl/frontend/bpu/GSharePredictor.sv
rtl/frontend/bpu/ReturnAddressStack.sv
rtl/frontend/bpu/TageFoldedHistory.sv
rtl/frontend/bpu/TageHash.sv
rtl/frontend/bpu/TageUpdateQueue.sv
rtl/frontend/bpu/TageTable.sv
rtl/frontend/bpu/StatisticalCorrector.sv
rtl/frontend/bpu/TagePredictor.sv
rtl/frontend/bpu/BranchPredictionUnit.sv
rtl/frontend/fetch/DualIF_IDRegister.sv
rtl/frontend/fetch/DualIfStages.sv
rtl/frontend/decode/IdStages.sv
