interface IdExeBusIf;
    import TypesPkg::*;

    logic              valid;
    instruction_addr_t pc;
    logic              registerWriteEnable;
    logic              dataWriteEnable;
    wb_select_t        wbSelect;
    csr_op_t           csrOp;
    csr_addr_t         csrAddr;
    logic              csrUseImm;
    word_t             csrImm;
    branch_ctr_t       branchCtr;
    alu_ctr_t          aluCtr;
    mem_access_t       memCtr;
    logic              aluSrcASelect;
    logic              aluSrcBSelect;
    logic              useRs1;
    logic              useRs2;
    word_t             dataA;
    word_t             dataB;
    reg_addr_t         regA;
    reg_addr_t         regB;
    reg_addr_t         rd;
    instruction_addr_t immediate;

    modport decode(
        output pc,
        output valid,
        output registerWriteEnable,
        output dataWriteEnable,
        output wbSelect,
        output csrOp,
        output csrAddr,
        output csrUseImm,
        output csrImm,
        output branchCtr,
        output aluCtr,
        output memCtr,
        output aluSrcASelect,
        output aluSrcBSelect,
        output useRs1,
        output useRs2,
        output regA,
        output regB,
        output rd,
        output immediate
    );

    modport register_in(
        input pc,
        input valid,
        input registerWriteEnable,
        input dataWriteEnable,
        input wbSelect,
        input csrOp,
        input csrAddr,
        input csrUseImm,
        input csrImm,
        input branchCtr,
        input aluCtr,
        input memCtr,
        input aluSrcASelect,
        input aluSrcBSelect,
        input useRs1,
        input useRs2,
        input dataA,
        input dataB,
        input regA,
        input regB,
        input rd,
        input immediate
    );

    modport register_out(
        output pc,
        output valid,
        output registerWriteEnable,
        output dataWriteEnable,
        output wbSelect,
        output csrOp,
        output csrAddr,
        output csrUseImm,
        output csrImm,
        output branchCtr,
        output aluCtr,
        output memCtr,
        output aluSrcASelect,
        output aluSrcBSelect,
        output useRs1,
        output useRs2,
        output dataA,
        output dataB,
        output regA,
        output regB,
        output rd,
        output immediate
    );

    modport sink(
        input pc,
        input valid,
        input registerWriteEnable,
        input dataWriteEnable,
        input wbSelect,
        input csrOp,
        input csrAddr,
        input csrUseImm,
        input csrImm,
        input branchCtr,
        input aluCtr,
        input memCtr,
        input aluSrcASelect,
        input aluSrcBSelect,
        input useRs1,
        input useRs2,
        input dataA,
        input dataB,
        input regA,
        input regB,
        input rd,
        input immediate
    );
endinterface
